### ISSUE TITLE
some hints to pw3

### ISSUE THREAD

**Issue by CanRau** [ryancramerdesign/ProcessExportProfile#10]
it's missing

site/
init.php
ready.php
finished.php

and $config->sessionAllow = function() {} as of https://processwire.com/blog/posts/multi-instance-pw3/#more-session-control
weren't copied properly so it broke the installation of the profile after manually fixing and reloading the page (duplicate form submission) everything worked..

**Comment by gRegorLove** [comment]
I'm seeing the init/ready/finished files in the code [here](https://github.com/ryancramerdesign/ProcessExportProfile/blob/master/ProcessExportProfile.module#L407), but they're not being included in the export for me for some reason.

**Comment by CanRau** [comment]
hmm..I only used export to directory which resulted in those missing files..
