### ISSUE TITLE
New option to update existing site profile does not delete removed files

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessExportProfile#18]
Hi @ryancramerdesign 

I just wanted to update my RockFrontend site profile and thought everything worked properly. Then I realised that my profile contained a file /site/templates/layout.less which my new site profile did not have any more.

Turned out that this file still existed in /site/assets/backups/export-profile/site-rockfrontend/templates/layout.less

Could this please be fixed so that all files that are removed from the new version of the site profile are also removed from the exported/updated site profile? This would be quite critical, because if that's not implemented the whole update feature is worthless as we'd have to compare all files manually :(

Thx in advance!

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock I thought we fixed this issue in v501 here: https://github.com/ryancramerdesign/ProcessExportProfile/commit/e935669fb816328f6c0365e13ab5d01d1cddb116

Are you already running this version?

**Comment by BernhardBaumrock** [comment]
You are absolutely right, just forgot to upgrade! Sorry :|
